import { useParams, useNavigate, Link } from 'react-router';
import { useStore } from '../../store/useStore';
import { Card, CardContent } from '../../components/ui/Card';
import { Button } from '../../components/ui/Button';
import { ArrowLeft, Send, CreditCard, FileText, Download } from 'lucide-react';
import { formatCurrency } from '../../lib/utils';
import { format } from 'date-fns';
import type { InvoiceStatus } from '../../types';

export default function InvoiceDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { invoices, clients, payments, updateInvoice } = useStore();

  const invoice = invoices.find(inv => inv.id === id);
  const client = invoice ? clients.find(c => c.id === invoice.clientId) : null;
  const invoicePayments = payments.filter(p => p.invoiceId === id).sort((a, b) => b.createdAt - a.createdAt);

  if (!invoice) {
    return (
      <div className="flex flex-col items-center justify-center py-20">
        <FileText className="w-16 h-16 text-slate-300 mb-4" />
        <p className="text-xl font-bold text-slate-900">Invoice not found</p>
        <Button variant="outline" className="mt-4" onClick={() => navigate('/billing')}>Back to Billing</Button>
      </div>
    );
  }

  const statusColor = (s: string) => {
    switch (s) {
      case 'Paid': return 'bg-green-100 text-green-700';
      case 'Sent': return 'bg-blue-100 text-blue-700';
      case 'Partially Paid': return 'bg-amber-100 text-amber-700';
      case 'Overdue': return 'bg-red-100 text-red-700';
      default: return 'bg-slate-100 text-slate-700';
    }
  };

  const handleStatusChange = (newStatus: InvoiceStatus) => {
    updateInvoice(invoice.id, { status: newStatus });
  };

  const handlePdfExport = async () => {
    // Load jsPDF + AutoTable via CDN (same pattern as QuoteBuilder)
    const loadScript = (src: string): Promise<void> => new Promise((resolve, reject) => {
      if (document.querySelector(`script[src="${src}"]`)) { resolve(); return; }
      const s = document.createElement('script');
      s.src = src; s.async = true; s.onload = () => resolve(); s.onerror = reject;
      document.body.appendChild(s);
    });
    await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js');
    await loadScript('https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.2/jspdf.plugin.autotable.min.js');

    const { jsPDF } = (window as any).jspdf;
    const doc = new jsPDF();
    const safeCurrency = (amount: number) => formatCurrency(amount).replace('₹', 'Rs. ');

    doc.setFontSize(20); doc.setFont("helvetica", "bold"); doc.setTextColor(15, 23, 42);
    doc.text(invoice.invoiceNumber, 14, 22);
    doc.setFontSize(18); doc.setTextColor(148, 163, 184);
    doc.text("INVOICE", 195, 20, { align: "right" });

    doc.setFontSize(10); doc.setFont("helvetica", "normal"); doc.setTextColor(100, 116, 139);
    doc.text(`Client: ${client?.name || 'N/A'}`, 14, 32);
    doc.text(`Issue: ${format(invoice.issueDate, 'MMM dd, yyyy')}`, 14, 38);
    doc.text(`Due: ${format(invoice.dueDate, 'MMM dd, yyyy')}`, 14, 44);
    doc.text(`Status: ${invoice.status}`, 14, 50);

    (doc as any).autoTable({
      startY: 58,
      head: [['#', 'DESCRIPTION', 'QTY', 'RATE', 'TOTAL']],
      body: invoice.items.map((item, i) => [i + 1, item.description, item.quantity, safeCurrency(item.unitPrice), safeCurrency(item.total)]),
      theme: 'plain',
      headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 9, textColor: [15, 23, 42], cellPadding: 5 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      columnStyles: { 0: { halign: 'center' }, 4: { halign: 'right', fontStyle: 'bold' } },
    });

    const finalY = (doc as any).lastAutoTable?.finalY || 80;
    doc.setFontSize(9); doc.setFont("helvetica", "bold"); doc.setTextColor(100, 116, 139);
    doc.text(`Subtotal: ${safeCurrency(invoice.subtotal)}`, 195, finalY + 10, { align: "right" });
    doc.text(`Discount: -${safeCurrency(invoice.discountAmount)}`, 195, finalY + 16, { align: "right" });
    doc.text(`Tax: ${safeCurrency(invoice.taxAmount)}`, 195, finalY + 22, { align: "right" });
    doc.setFontSize(14); doc.setTextColor(15, 23, 42);
    doc.text(`Total: ${safeCurrency(invoice.total)}`, 195, finalY + 32, { align: "right" });

    doc.setFontSize(8); doc.setTextColor(148, 163, 184);
    doc.text("Generated by Quoteit", 105, doc.internal.pageSize.height - 10, { align: "center" });
    doc.save(`${invoice.invoiceNumber}.pdf`);
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" onClick={() => navigate('/billing')}><ArrowLeft className="w-4 h-4" /></Button>
        <div className="flex-1">
          <h1 className="text-3xl font-black tracking-tighter text-slate-900">{invoice.invoiceNumber}</h1>
          <p className="text-slate-500 mt-1">{client?.name || 'Unknown Client'}</p>
        </div>
        <span className={`px-3 py-1.5 rounded text-xs font-black uppercase tracking-wider ${statusColor(invoice.status)}`}>{invoice.status}</span>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card><CardContent className="p-5"><p className="text-[10px] uppercase font-bold tracking-widest text-slate-400">Total</p><p className="text-2xl font-black mt-1 text-slate-900">{formatCurrency(invoice.total)}</p></CardContent></Card>
        <Card><CardContent className="p-5"><p className="text-[10px] uppercase font-bold tracking-widest text-slate-400">Paid</p><p className="text-2xl font-black mt-1 text-green-700">{formatCurrency(invoice.amountPaid)}</p></CardContent></Card>
        <Card><CardContent className="p-5"><p className="text-[10px] uppercase font-bold tracking-widest text-slate-400">Balance Due</p><p className="text-2xl font-black mt-1 text-red-600">{formatCurrency(invoice.balanceDue)}</p></CardContent></Card>
        <Card><CardContent className="p-5"><p className="text-[10px] uppercase font-bold tracking-widest text-slate-400">Due Date</p><p className="text-2xl font-black mt-1 text-slate-900">{format(invoice.dueDate, 'MMM dd, yyyy')}</p></CardContent></Card>
      </div>

      {/* Actions */}
      <div className="flex flex-wrap gap-3">
        {invoice.status === 'Draft' && <Button variant="primary" className="gap-2" onClick={() => handleStatusChange('Sent')}><Send className="w-4 h-4" /> Mark as Sent</Button>}
        {(invoice.status !== 'Paid') && <Link to={`/payments/new?invoiceId=${invoice.id}`}><Button variant="primary" className="gap-2"><CreditCard className="w-4 h-4" /> Record Payment</Button></Link>}
        {invoice.status === 'Sent' && <Button variant="outline" className="gap-2" onClick={() => handleStatusChange('Overdue')}>Mark Overdue</Button>}
        <Button variant="outline" className="gap-2" onClick={handlePdfExport}><Download className="w-4 h-4" /> Export PDF</Button>
      </div>

      {/* Line Items */}
      <Card>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead className="border-b border-slate-200">
              <tr className="text-[10px] uppercase font-bold tracking-widest text-slate-400 bg-slate-50">
                <th className="px-6 py-4">#</th><th className="px-6 py-4">Description</th><th className="px-6 py-4">Qty</th><th className="px-6 py-4">Rate</th><th className="px-6 py-4 text-right">Total</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-sm text-slate-700">
              {invoice.items.map((item, idx) => (
                <tr key={item.id} className="hover:bg-slate-50"><td className="px-6 py-4 text-slate-400">{idx + 1}</td><td className="px-6 py-4 font-medium">{item.description}</td><td className="px-6 py-4">{item.quantity}</td><td className="px-6 py-4">{formatCurrency(item.unitPrice)}</td><td className="px-6 py-4 text-right font-bold">{formatCurrency(item.total)}</td></tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="border-t border-slate-200 p-6 space-y-2">
          <div className="flex justify-between text-sm"><span className="text-slate-500">Subtotal</span><span className="font-bold">{formatCurrency(invoice.subtotal)}</span></div>
          <div className="flex justify-between text-sm"><span className="text-slate-500">Discount</span><span className="font-bold">−{formatCurrency(invoice.discountAmount)}</span></div>
          <div className="flex justify-between text-sm"><span className="text-slate-500">Tax</span><span className="font-bold">{formatCurrency(invoice.taxAmount)}</span></div>
          <div className="flex justify-between text-lg pt-2 border-t border-slate-100"><span className="font-black">Grand Total</span><span className="font-black">{formatCurrency(invoice.total)}</span></div>
        </div>
      </Card>

      {/* Payments */}
      <div><h2 className="text-xl font-bold tracking-tight text-slate-900 mb-4">Payment History</h2>
        <Card><div className="overflow-x-auto"><table className="w-full text-left border-collapse">
          <thead className="border-b border-slate-200"><tr className="text-[10px] uppercase font-bold tracking-widest text-slate-400 bg-slate-50"><th className="px-6 py-4">Date</th><th className="px-6 py-4">Method</th><th className="px-6 py-4">Reference</th><th className="px-6 py-4 text-right">Amount</th></tr></thead>
          <tbody className="divide-y divide-slate-100 text-sm text-slate-700">
            {invoicePayments.length === 0 ? (<tr><td colSpan={4} className="px-6 py-8 text-center text-slate-500">No payments recorded yet.</td></tr>) : (
              invoicePayments.map(p => (<tr key={p.id} className="hover:bg-slate-50"><td className="px-6 py-4">{format(p.paymentDate, 'MMM dd, yyyy')}</td><td className="px-6 py-4"><span className="px-2 py-0.5 rounded text-[10px] font-black uppercase bg-slate-100 text-slate-700">{p.paymentMethod}</span></td><td className="px-6 py-4 text-slate-500">{p.referenceNumber || '—'}</td><td className="px-6 py-4 text-right font-bold text-green-700">{formatCurrency(p.amount)}</td></tr>))
            )}
          </tbody>
        </table></div></Card>
      </div>
    </div>
  );
}
